[pytest]
testpaths = apps
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = --strict-markers --tb=short -v
DJANGO_SETTINGS_MODULE = backend.settings.development
