# Generated by Django 5.2.16 on 2026-07-22 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="logincode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("used_at__isnull", True)),
                fields=("user",),
                name="one_unused_login_code_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentity",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="unique_user_platform_identity"
            ),
        ),
    ]
